### ISSUE TITLE
libepoxy: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [anholt/libepoxy#244]
```
+ cd libepoxy-1.5.5
+ xvfb-run -d -s '-screen 0 640x480x24' /usr/bin/meson test -C x86_64-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/libepoxy-1.5.5/x86_64-redhat-linux-gnu'
ninja: no work to do.
 1/17 header_guards                           OK              0.15s
 2/17 misc_defines                            OK              0.14s
 3/17 khronos_typedefs                        OK              0.14s
 4/17 gl_version                              OK              0.13s
 5/17 egl_has_extension_nocontext             OK              0.13s
 6/17 egl_epoxy_api                           OK              0.12s
 7/17 egl_gles1_without_glx                   OK              0.11s
 8/17 egl_gles2_without_glx                   OK              0.10s
 9/17 egl_gl                                  OK              0.10s
10/17 glx_glxgetprocaddress_nocontext         OK              0.08s
11/17 glx_public_api                          OK              0.10s
12/17 glx_has_extension_nocontext             OK              0.08s
13/17 glx_public_api_core                     OK              0.10s
14/17 glx_alias_prefer_same_name              OK              0.08s
15/17 glx_shared_znow                         OK              0.10s
16/17 glx_gles2                               OK              0.09s
17/17 glx_beginend                            FAIL            1.91s   killed by signal 11 SIGSEGV
>>> MALLOC_PERTURB_=131 /home/tkloczko/rpmbuild/BUILD/libepoxy-1.5.5/x86_64-redhat-linux-gnu/test/glx_beginend


Summary of Failures:

17/17 glx_beginend                    FAIL            1.91s   killed by signal 11 SIGSEGV
```
```
[tkloczko@barrel SPECS]$ coredumpctl gdb 21351
           PID: 21351 (glx_beginend)
           UID: 1000 (tkloczko)
           GID: 1000 (tkloczko)
        Signal: 11 (SEGV)
     Timestamp: Tue 2021-03-16 17:28:09 GMT (22s ago)
  Command Line: /home/tkloczko/rpmbuild/BUILD/libepoxy-1.5.5/x86_64-redhat-linux-gnu/test/glx_beginend
    Executable: /home/tkloczko/rpmbuild/BUILD/libepoxy-1.5.5/x86_64-redhat-linux-gnu/test/glx_beginend
 Control Group: /user.slice/user-1000.slice/session-11.scope
          Unit: session-11.scope
         Slice: user-1000.slice
       Session: 11
     Owner UID: 1000 (tkloczko)
       Boot ID: cfd9f1bf7ff54318b8b639abab38ccb6
    Machine ID: d033f66b249a4ec09acfa81ac205554f
      Hostname: barrel
       Storage: /var/lib/systemd/coredump/core.glx_beginend.1000.cfd9f1bf7ff54318b8b639abab38ccb6.21351.1615915689000000.zst
       Message: Process 21351 (glx_beginend) of user 1000 dumped core.

                Stack trace of thread 21351:
                #0  0x00007f383b9dc645 ralloc_steal (swrast_dri.so + 0x12f645)
                #1  0x00007f383ba4767e steal_memory (swrast_dri.so + 0x19a67e)
                #2  0x00007f383ba47b5d _ZN23ir_hierarchical_visitor11visit_enterEP7ir_loop (swrast_dri.so + 0x19ab5d)
                #3  0x00007f383ba47e9d _ZN11ir_function6acceptEP23ir_hierarchical_visitor (swrast_dri.so + 0x19ae9d)
                #4  0x00007f383bb6095e _Z11reparent_irP9exec_listPv.isra.0 (swrast_dri.so + 0x2b395e)
                #5  0x00007f383c6a850d create_new_program (swrast_dri.so + 0xdfb50d)
                #6  0x00007f383c6aa777 update_program (swrast_dri.so + 0xdfd777)
                #7  0x00007f383c6ad797 _mesa_update_state (swrast_dri.so + 0xe00797)
                #8  0x00007f383c6ae6dd _mesa_valid_to_render (swrast_dri.so + 0xe016dd)
                #9  0x00007f383c6b5cfb vbo_exec_Begin (swrast_dri.so + 0xe08cfb)
                #10 0x0000556fba5d42db n/a (/home/tkloczko/rpmbuild/BUILD/libepoxy-1.5.5/x86_64-redhat-linux-gnu/test/glx_beginend + 0x12db)

GNU gdb (GDB) Fedora 9.0.50.20191119-2.fc32
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/tkloczko/rpmbuild/BUILD/libepoxy-1.5.5/x86_64-redhat-linux-gnu/test/glx_beginend...
[New LWP 21351]
[New LWP 21549]
[New LWP 21550]
[New LWP 21551]
[New LWP 21559]
[New LWP 21546]
[New LWP 21556]
[New LWP 21545]
[New LWP 21548]
[New LWP 21565]
[New LWP 21566]
[New LWP 21563]
[New LWP 21571]
[New LWP 21573]
[New LWP 21569]
[New LWP 21558]
[New LWP 21560]
[New LWP 21547]
[New LWP 21572]
[New LWP 21564]
[New LWP 21570]
[New LWP 21568]
[New LWP 21567]
[New LWP 21576]
[New LWP 21562]
[New LWP 21553]
[New LWP 21574]
[New LWP 21554]
[New LWP 21581]
[New LWP 21580]
[New LWP 21561]
[New LWP 21575]
[New LWP 21552]
[New LWP 21555]
[New LWP 21578]
[New LWP 21579]
[New LWP 21557]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libGLX_mesa.so.0
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/0a/ca25a6a512948f53535e36007812dbc037474d.debug
Missing separate debuginfo for /lib64/libglapi.so.0
Try: dnf --enablerepo='*debug*' install /usr/lib/debug/.build-id/9d/5123a91c2c03b3cb6ccfc3dba636c11e7bbdbb.debug
 elfutils-libelf-0.183-3.1.fc35.x86_64 expat-2.2.10-3.fc35.x86_64 glibc-2.33.9000-1.fc35.x86_64 libX11-1.7.0-4.fc35.x86_64 libX11-xcb-1.7.0-4.fc35.x86_64 libXau-1.0.9-7.fc35.x86_64 libXdmcp-1.1.3-7.fc35.x86_64 libXext-1.3.4-7.fc35.x86_64 libXfixes-5.0.3-14.fc34.x86_64 libXxf86vm-1.1.4-16.fc34.x86_64 libdrm-2.4.104-2.fc34.x86_64 libedit-3.1-36.20191231cvs.fc35.x86_64 libffi-3.2.1-2.3.fc32.x86_64 libgcc-11.0.0-0.19.fc35.x86_64 libglvnd-1.3.2-3.2.fc34.x86_64 libglvnd-glx-1.3.2-3.2.fc34.x86_64 libglvnd-opengl-1.3.2-3.2.fc34.x86_64 libselinux-3.2-2.fc35.x86_64 libstdc++-11.0.0-0.19.fc35.x86_64 libxcb-1.14-7.fc34.x86_64 libxml2-2.9.10-10.fc35.x86_64 libxshmfence-1.3-8.fc34.x86_64 libzstd-1.4.9-2.fc35.x86_64 pcre2-10.36-5.fc35.x86_64 sssd-libs-2.4.0-3.1.fc34.x86_64 zlib-1.2.11-26.fc35.x86_64
--Type <RET> for more, q to quit, c to continue without paging--
Missing separate debuginfos, use: dnf debuginfo-installCore was generated by `/home/tkloczko/rpmbuild/BUILD/libepoxy-1.5.5/x86_64-redhat-linux-gnu/test/glx_b'.
Program terminated with signal SIGSEGV, Segmentation fault.

#0  unlink_block (info=<optimized out>) at ../src/util/ralloc.c:326
326        info = get_header(ptr);
[Current thread is 1 (Thread 0x7f383d388740 (LWP 21351))]
(gdb)
(gdb) bt full
#0  unlink_block (info=<optimized out>) at ../src/util/ralloc.c:326
No locals.
#1  ralloc_steal (new_ctx=new_ctx@entry=0x556fbc34f570, ptr=ptr@entry=0x7c7c7c7c7c7c7c7c) at ../src/util/ralloc.c:329
        info = <optimized out>
        parent = <optimized out>
#2  0x00007f383ba4767e in steal_memory (ir=0x556fbc35db30, new_ctx=0x556fbc34f570) at ../src/compiler/glsl/ir.cpp:2269
        fn = <error reading variable fn (dwarf2_find_location_expression: Corrupted DWARF expression.)>
        constant = 0x0
#3  0x00007f383ba47b5d in ir_hierarchical_visitor::visit_enter (this=<optimized out>, ir=<optimized out>) at ../src/compiler/glsl/ir_hierarchical_visitor.cpp:89
No locals.
#4  0x00007f383ba47e9d in ir_function::accept (this=0x556fbc35db30, v=0x7fff0ccf1a50) at ../src/compiler/glsl/ir_hv_accept.cpp:123
        s = <optimized out>
#5  0x00007f383bb6095e in visit_tree (data_leave=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>,
    callback_leave=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>,
    data_enter=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>,
    callback_enter=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>,
    ir=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>) at ../src/compiler/glsl/ir_hierarchical_visitor.cpp:402
        v = {_vptr.ir_hierarchical_visitor = 0x7f383cd210f0 <vtable for ir_hierarchical_visitor+16>, base_ir = 0x0,
          callback_enter = 0x7f383ba47610 <steal_memory(ir_instruction*, void*)>, callback_leave = 0x0, data_enter = 0x556fbc34f570, data_leave = 0x0, in_assignee = false}
#6  reparent_ir (mem_ctx=0x556fbc34f570, list=<optimized out>, list=<optimized out>) at ../src/compiler/glsl/ir.cpp:2289
        node = 0x556fbc35db30
#7  0x00007f383c6a850d in create_new_program (ctx=<optimized out>, key=<optimized out>) at ../src/mesa/main/ff_fragment_shader.cpp:1113
        p = {<ir_builder::ir_factory> = {instructions = 0x556fbc35dcc0, mem_ctx = 0x556fbc115b70}, shader_program = 0x556fbc068740, shader = 0x556fbc1c7390,
          top_instructions = 0x556fbc34f570, state = 0x7fff0ccf1e50, src_texture = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, src_previous = 0x0}
        unit = <error reading variable unit (dwarf2_find_location_expression: Corrupted DWARF expression.)>
        state = <optimized out>
        main_f = <optimized out>
        main_sig = <optimized out>
        options = 0x7f382d4f39b8
#8  0x00007f383c6aa777 in _mesa_get_fixed_func_fragment_program (ctx=0x7f382d4de010) at ../src/mesa/main/ff_fragment_shader.cpp:1152
        shader_program = <optimized out>
        key = {nr_enabled_units = 0, separate_specular = 0, fog_mode = 0, inputs_available = 2, num_draw_buffers = 1, unit = {{enabled = 0, source_index = 0, shadow = 0,
              ModeRGB = 0, ModeA = 0, ScaleShiftRGB = 0, ScaleShiftA = 0, NumArgsRGB = 0, NumArgsA = 0, ArgsRGB = {{Source = 0 '\000', Operand = 0 '\000'}, {
                  Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}, ArgsA = {{Source = 0 '\000',
                  Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}}, {
              enabled = 0, source_index = 0, shadow = 0, ModeRGB = 0, ModeA = 0, ScaleShiftRGB = 0, ScaleShiftA = 0, NumArgsRGB = 0, NumArgsA = 0, ArgsRGB = {{
                  Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000',
                  Operand = 0 '\000'}}, ArgsA = {{Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000',
                  Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}}, {enabled = 0, source_index = 0, shadow = 0, ModeRGB = 0, ModeA = 0, ScaleShiftRGB = 0,
              ScaleShiftA = 0, NumArgsRGB = 0, NumArgsA = 0, ArgsRGB = {{Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {
                  Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}, ArgsA = {{Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000',
                  Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}}, {enabled = 0, source_index = 0, shadow = 0,
              ModeRGB = 0, ModeA = 0, ScaleShiftRGB = 0, ScaleShiftA = 0, NumArgsRGB = 0, NumArgsA = 0, ArgsRGB = {{Source = 0 '\000', Operand = 0 '\000'}, {
                  Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}, ArgsA = {{Source = 0 '\000',
                  Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}}, {
              enabled = 0, source_index = 0, shadow = 0, ModeRGB = 0, ModeA = 0, ScaleShiftRGB = 0, ScaleShiftA = 0, NumArgsRGB = 0, NumArgsA = 0, ArgsRGB = {{
                  Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000',
                  Operand = 0 '\000'}}, ArgsA = {{Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000',
                  Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}}, {enabled = 0, source_index = 0, shadow = 0, ModeRGB = 0, ModeA = 0, ScaleShiftRGB = 0,
              ScaleShiftA = 0, NumArgsRGB = 0, NumArgsA = 0, ArgsRGB = {{Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {
                  Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}, ArgsA = {{Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000',
                  Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}}, {enabled = 0, source_index = 0, shadow = 0,
              ModeRGB = 0, ModeA = 0, ScaleShiftRGB = 0, ScaleShiftA = 0, NumArgsRGB = 0, NumArgsA = 0, ArgsRGB = {{Source = 0 '\000', Operand = 0 '\000'}, {
                  Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}, ArgsA = {{Source = 0 '\000',
                  Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}}, {
--Type <RET> for more, q to quit, c to continue without paging--
              enabled = 0, source_index = 0, shadow = 0, ModeRGB = 0, ModeA = 0, ScaleShiftRGB = 0, ScaleShiftA = 0, NumArgsRGB = 0, NumArgsA = 0, ArgsRGB = {{
                  Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000',
                  Operand = 0 '\000'}}, ArgsA = {{Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}, {Source = 0 '\000',
                  Operand = 0 '\000'}, {Source = 0 '\000', Operand = 0 '\000'}}}}}
        keySize = 4
        shader_program = <optimized out>
        key = <optimized out>
        keySize = <optimized out>
#9  update_program (ctx=ctx@entry=0x7f382d4de010) at ../src/mesa/main/state.c:263
        f = <optimized out>
        vsProg = 0x0
        tcsProg = 0x0
        tesProg = 0x0
        gsProg = 0x0
        fsProg = <optimized out>
        csProg = 0x0
        prevVP = 0x0
        prevFP = 0x0
        prevGP = 0x0
        prevTCP = 0x0
        prevTEP = 0x0
        prevCP = 0x0
#10 0x00007f383c6ad797 in _mesa_update_state_locked (ctx=0x7f382d4de010) at ../src/mesa/main/state.c:509
        prog_flags = 2221607245
        new_state = <optimized out>
        new_prog_state = 0
        computed_states = 4286578175
        new_state = <optimized out>
        new_prog_state = <optimized out>
        computed_states = <optimized out>
        prog_flags = <optimized out>
#11 _mesa_update_state (ctx=0x7f382d4de010) at ../src/mesa/main/state.c:542
No locals.
#12 0x00007f383c6ae6dd in _mesa_valid_to_render (ctx=ctx@entry=0x7f382d4de010, where=where@entry=0x7f383c858288 "glBegin") at ../src/mesa/main/draw_validate.c:130
No locals.
#13 0x00007f383c6b5cfb in vbo_exec_Begin (mode=4) at ../src/mesa/vbo/vbo_exec_api.c:826
        ctx = 0x7f382d4de010
        vbo = 0x7f382d5193d0
        exec = 0x7f382d519980
        i = <error reading variable i (dwarf2_find_location_expression: Corrupted DWARF expression.)>
#14 0x0000556fba5d42db in test_with_epoxy () at ../test/glx_beginend.c:103
No locals.
#15 main (argc=<optimized out>, argv=<optimized out>) at ../test/glx_beginend.c:103
        pass = true
(gdb)
```

**Comment by ebassi** [comment]
The crash is in Mesa, in the swrast driver.

**Comment by kloczek** [comment]
Sh*t .. why I've not spotted that? :/
Sorry.
